version: '3.7'

services:

  web:
    build: './docker/web'
    container_name: edu-db-app
    ports:
      - '8080:80'
    volumes:
      - './:/var/www/html'
    links:
      - db
      - adminer

  adminer:
    image: adminer
    container_name: edu-db-admin
    ports:
      - 8888:8080
    links:
      - db 

  db:
    image: mysql
    container_name: edu-db-mysql
    ports:
      - '3306:3306'
    volumes:
      - './docker/database:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: materials
      MYSQL_ROOT_PASSWORD: root

